name: CI Pipeline

on:
    push:
        branches:
            - develop
            - master

jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Node and Dependencies
              uses: ./.github/actions/setup-node-and-dependencies

            - name: Run Format
              run: |
                  npm run format
                  git diff --exit-code

    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Node and Dependencies
              uses: ./.github/actions/setup-node-and-dependencies

            - name: Run Tests with Coverage
              run: npm run test-coverage

            - name: Upload Coverage Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: test_coverage
                  path: coverage
                  overwrite: true

    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Node and Dependencies
              uses: ./.github/actions/setup-node-and-dependencies

            - name: Run Build
              run: npm run build

            - name: Upload Bundle Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: rollup_bundle_stats
                  path: rollup_bundle_stats.html
                  overwrite: true
